export default defaultPopupData = {
  selectType: [
    {id: 1, title: 'Recidencial', isSelected: false},
    {id: 2, title: 'Apartment', isSelected: false},
    {id: 3, title: 'Office', isSelected: false},
    {id: 4, title: 'Farm House', isSelected: false},
    {id: 5, title: 'Shop', isSelected: false},
    {id: 6, title: 'Pent House', isSelected: false},
  ],
  roomType: [
    {id: 1, title: '1BHK', isSelected: false},
    {id: 2, title: '2BHK', isSelected: false},
    {id: 3, title: '3BHK', isSelected: false},
    {id: 4, title: '4BHK', isSelected: false},
  ],
  facilityType: [
    {id: 1, title: 'Swimming Pool', isSelected: false},
    {id: 2, title: 'Garden', isSelected: false},
    {id: 3, title: 'Theater', isSelected: false},
    {id: 4, title: 'Gaming', isSelected: false},
  ],
  communityNeighborsData: [
    {
      id: 1,
      title: 'Select',
      isSelected: false,
      error: null,
      data: [
        {id: 1, title: 'Hindu', isSelected: false},
        {id: 2, title: 'Muslim', isSelected: false},
        {id: 3, title: 'Punjabi', isSelected: false},
        {id: 4, title: 'Christian', isSelected: false},
        {id: 5, title: 'Other', isSelected: false},
        {id: 6, title: 'None', isSelected: false},
      ],
    },
    {
      id: 2,
      title: 'Dieting',
      isSelected: false,
      error: null,
      data: [
        {id: 1, title: 'Vegetarian', isSelected: false},
        {id: 2, title: 'Non-Vegetarian', isSelected: false},
      ],
    },
  ],
  // selectType: [
  //   {id: 1, title: 'Recidencial', isSelected: false},
  //   {id: 2, title: 'Apartment', isSelected: false},
  //   {id: 3, title: 'Office', isSelected: false},
  //   {id: 4, title: 'Farm House', isSelected: false},
  //   {id: 5, title: 'Shop', isSelected: false},
  //   {id: 6, title: 'Pent House', isSelected: false},
  // ],
  // roomType: [
  //   {id: 1, title: '1BHK', isSelected: false},
  //   {id: 2, title: '2BHK', isSelected: false},
  //   {id: 3, title: '3BHK', isSelected: false},
  //   {id: 4, title: '4BHK', isSelected: false},
  // ],
  areaType: [
    {id: 1, title: 'Peaceful', isSelected: false},
    {id: 2, title: 'Crowded', isSelected: false},
    {id: 3, title: 'Mixed', isSelected: false},
  ],
  dietaryPreference: [
    {id: 1, title: 'Vegetarian', isSelected: false},
    {id: 2, title: 'Non-Vegetarian', isSelected: false},
  ],
  religionType: [
    {id: 1, title: 'Hindu', isSelected: false},
    {id: 2, title: 'Muslim', isSelected: false},
    {id: 3, title: 'Punjabi', isSelected: false},
    {id: 4, title: 'Christian', isSelected: false},
    {id: 5, title: 'Other', isSelected: false},
    {id: 6, title: 'None', isSelected: false},
  ],
  homeDetails: [
    {id: 1, title: 'Home Type', subTitle: '2 BHK'},
    {id: 2, title: 'Area Type', subTitle: 'Peaceful'},
    {id: 3, title: 'Dietary Preference', subTitle: 'Vegetarian'},
    {id: 4, title: 'Rent Per Month', subTitle: '10000'},
    {id: 5, title: 'Religion', subTitle: 'Hindu'},
    {id: 6, title: 'Deposite', subTitle: '20000'},
  ],
  facilities: [
    {id: 1, title: 'Pet Friendly'},
    {id: 2, title: 'Kitchen Furnished'},
    {id: 3, title: 'Furnished'},
    {id: 4, title: 'Swimming Pool'},
    {id: 5, title: 'Garden'},
    {id: 6, title: 'Gaming'},
    {id: 7, title: 'Theater'},
    {id: 8, title: 'Free Wi-Fi'},
    {id: 9, title: 'Parking Area'},
    {id: 10, title: 'Gallery Area'},
  ],
  advantages: [
    {id: 1, title: 'Sea View'},
    {id: 2, title: 'River Front'},
    {id: 3, title: 'Eco Friendly'},
  ],
  nearBy: [
    {id: 1, title: 'School'},
    {id: 2, title: 'Mall'},
    {id: 3, title: 'Airport'},
    {id: 4, title: 'Beach'},
    {id: 5, title: 'Hospital'},
    {id: 6, title: 'Cinema'},
    {id: 7, title: 'Garden'},
    {id: 8, title: 'Restaurant'},
    {id: 9, title: 'Market'},
  ],
};
